# Generated by Django 5.2.6 on 2026-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image_url_lesson_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_minted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='school_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
