# Generated by Django 5.2.4 on 2026-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_minted_course_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
