# Generated by Django 5.2.4 on 2026-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_sovereignschool_course_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
