# Generated by Django 5.2.4 on 2026-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessonprogress_layout_config_lessonprogress_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='metadata_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('claimed', 'Claimed On-Chain')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='token_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
