# Generated by Django 5.2.6 on 2026-04-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_certificate_image_uri_certificate_metadata_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='division',
            field=models.CharField(choices=[('builders', 'Builders Division'), ('creatives', 'Creatives Division'), ('both', 'Both (Builders & Creatives)'), ('neither', 'Neither (General/Core)')], default='neither', max_length=20),
        ),
    ]
