# Generated by Django 5.2.4 on 2026-05-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_category_course_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
