# Generated by Django 5.2.4 on 2026-05-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBubble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('concept', models.TextField()),
                ('source_file', models.FileField(blank=True, null=True, upload_to='study_bubbles/sources/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=list)),
                ('video_refs', models.JSONField(blank=True, default=list)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_bubbles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
