# Generated by Django 5.2.4 on 2026-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_fiat_price_alter_enrollment_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
