# Generated by Django 5.2.4 on 2026-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authwallet', '0002_walletuser_display_name_walletuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='github_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='is_wallet_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
