# Generated by Django 5.2.4 on 2026-06-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authwallet', '0003_walletuser_bio_walletuser_github_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='is_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='org_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='org_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
