# Generated by Django 5.2.6 on 2026-06-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authwallet', '0004_walletuser_is_institution_walletuser_org_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
