# Generated by Django 5.2.4 on 2026-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authwallet", "0005_walletuser_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletuser",
            name="adisanlo_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="walletuser",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="walletuser",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="walletuser",
            name="subscription_status",
            field=models.CharField(default="inactive", max_length=50),
        ),
    ]
