[package]
name = "wagmi_solana"
version = "0.1.0"
description = "Solana Anchor smart contract for Wagmi education platform"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "wagmi_solana"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = { version = "0.29.0", features = ["metadata", "token"] }
